spring:
   datasource:
     url: jdbc:mysql://localhost:3306/krystian_prod
     username: krystian_prod_user
     #    prod password should be environment variable
     password: krystian
     platform: mysql
   jpa:
     hibernate:
       ddl-auto: validate
     database-platform: org.hibernate.dialect.MySQL8Dialect
     database: mysql
     show-sql: false
